### ISSUE TITLE
Error "no apps generated" after build success.

### ISSUE THREAD

**Issue by SidiBecker** [bitrise-community/steps-ionic-archive#86]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.3.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME

### Issue description

Error: `no apps generated` after `** BUILD SUCCEEDED **`

Until version 2.3.1, the build was successful.

### Bitrise info

- Build URL: https://app.bitrise.io/build/40888bb1-c95d-4d92-9729-9357676ac5f5
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES 
- Log: 

<details>
  <pre>
      ** BUILD SUCCEEDED **
      no apps generated
  </pre>
</details>

### Steps to reproduce

.yml:
```
ionic-archive@2:
        inputs:
        - run_ionic_prepare: 'false'
        - target: emulator
        - platform: ios
```
